name: flutter_datalogic
description: A Flutter plugin for communicate with Datalogic scanners. Supports listen scanner
  status changed or receive data scanned by device have Datalogic services.
version: 1.0.9
homepage: https://github.com/tusaamf/flutter_datalogic

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.8.1
  uuid: ">=3.0.6 <5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.3.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.tusaamf.flutter_datalogic
        pluginClass: FlutterDatalogicPlugin